### ISSUE TITLE
Method to validate API key

### ISSUE THREAD

**Issue by Daniel15** [AssemblyAI/assemblyai-csharp-sdk#57]
It would be useful to have a method to validate that the API key is valid (i.e. just hit some unbilled API endpoint and ensure a successful response). On startup of my app, I want to validate the API keys of all third-party services so that it can immediately show an error about the API key being invalid, rather than having to wait until the API is actually used.

**Comment by Swimburger** [comment]
I think you could use `var page = await client.Transcripts.ListAsync();` for now.
I agree this would be a good addition.

**Comment by Daniel15** [comment]
Thanks! That works for me.
