### ISSUE TITLE
Detailed Documentation

### ISSUE THREAD

**Issue by ranjancse26** [AssemblyAI/assemblyai-csharp-sdk#6]
Please come up with the detailed documentation explaining the end to end aspects of the library with the code samples.

**Comment by Swimburger** [comment]
We plan to have documentation for the .NET SDK in all [our docs](https://www.assemblyai.com/docs/getting-started/transcribe-an-audio-file), and docs in the README, as we have with the other SDKs.

**Comment by Swimburger** [comment]
The README and docs now document the .NET SDK fully, and there's an [SDK API reference](https://assemblyai.github.io/assemblyai-csharp-sdk/).
