### ISSUE TITLE
Samples, Demo Apps

### ISSUE THREAD

**Issue by ranjancse26** [AssemblyAI/assemblyai-csharp-sdk#7]
Please plan on coming up with a ton of code samples. It could be a console, winform, web etc. Having an end to end sample makes more sense for the consumers.

**Comment by Swimburger** [comment]
We plan to have samples for the .NET SDK in all [our docs](https://www.assemblyai.com/docs/getting-started/transcribe-an-audio-file), as we have with the other SDKs.
I think it'd be good to have samples in the repo too, so I'll keep this open to tackle later.
