### ISSUE TITLE
Nuget - Package Not Found Error

### ISSUE THREAD

**Issue by ranjancse26** [AssemblyAI/assemblyai-csharp-sdk#8]
I happened to click on the nuget package on the Readme page and it took me to the package not found page.

[AssemblyAI.net](https://www.nuget.org/packages/AssemblyAI.net/)

<img width="844" alt="image" src="https://github.com/AssemblyAI/assemblyai-csharp-sdk/assets/2565797/371ca151-f0f7-4edc-98a7-320884fb47e4">

**Comment by dsinghvi** [comment]
@ranjancse26 we should have the package published by this week (just running a couple smoke tests this week)

**Comment by dsinghvi** [comment]
@ranjancse26 only a couple _weeks_ later... package is [here](https://www.nuget.org/packages/AssemblyAI/0.0.1-alpha#supportedframeworks-body-tab)!
